create table if not exists public.ml_watchlist (
    user_id uuid not null references auth.users(id) on delete cascade,
    launch_id text not null,
    created_at timestamptz not null default now(),
    primary key (user_id, launch_id)
);

create table if not exists public.ml_prediction_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    launch_id text not null,
    launch_name text not null,
    risk_score double precision not null check (risk_score between 0 and 1),
    risk_lower double precision,
    risk_upper double precision,
    prediction text not null,
    model_version text not null,
    created_at timestamptz not null default now()
);

create index if not exists ml_prediction_history_user_launch_idx
    on public.ml_prediction_history (user_id, launch_id, created_at desc);

create table if not exists public.ml_usage_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    event_type text not null,
    launch_id text,
    created_at timestamptz not null default now()
);

create index if not exists ml_usage_events_user_month_idx
    on public.ml_usage_events (user_id, event_type, created_at desc);

update public.subscription_plans
set description = case id
    when 'free' then 'Pour découvrir Artemis et tester le risque de lancement.'
    when 'pro' then 'Pour analyser, expliquer et comparer les risques.'
    when 'premium' then 'Pour surveiller les missions et produire des rapports professionnels.'
end;

delete from public.subscription_plan_features;

insert into public.subscription_plan_features (plan_id, feature, is_included, display_order)
values
    ('free', 'Dashboard, carte et tendances essentielles', true, 1),
    ('free', '3 analyses de risque par mois', true, 2),
    ('free', 'Décision et niveau de risque simplifié', true, 3),
    ('free', 'Score calibré, explications et comparateur', false, 4),
    ('free', 'Watchlist, alertes et rapports PDF', false, 5),
    ('pro', 'Analyses de risque illimitées', true, 1),
    ('pro', 'Score calibré et fourchette d incertitude', true, 2),
    ('pro', 'Explications et fiabilité historique', true, 3),
    ('pro', 'Comparateur et exports CSV', true, 4),
    ('pro', 'Watchlist, scénarios et rapports PDF', false, 5),
    ('premium', 'Toutes les fonctions Pro', true, 1),
    ('premium', 'Watchlist et alertes de changement de risque', true, 2),
    ('premium', 'Simulateur de scénarios', true, 3),
    ('premium', 'Rapports PDF et historique des prédictions', true, 4),
    ('premium', 'Monitoring détaillé du modèle', true, 5);
